import React from 'react';
import { ShieldCheck, Flame, BookOpen, Settings } from 'lucide-react';

const About = () => {
  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '3rem', maxWidth: '900px', margin: '0 auto', paddingBottom: '4rem' }}>
      <div style={{ textAlign: 'center' }}>
        <h1 style={{ fontSize: '2.5rem' }}>About EduLearn LMS</h1>
        <p style={{ color: '#9ca3af', marginTop: '0.5rem' }}>An enterprise-grade online education portal for students, instructors, and universities.</p>
      </div>

      <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <h2 style={{ fontSize: '1.4rem', color: '#fbbf24' }}>System Architecture Highlights</h2>
        <p>EduLearn is engineered using a robust MERN architecture with security controls, local asset buffers, and real-time Socket communication triggers.</p>
        
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginTop: '1rem' }}>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <div style={{ color: '#6366f1' }}><ShieldCheck size={24} /></div>
            <div>
              <h4 style={{ fontSize: '1rem' }}>Role-Based Access Guard</h4>
              <p style={{ fontSize: '0.85rem' }}>Protects student and grading rosters with cryptographically signed JSON Web Tokens (JWT).</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <div style={{ color: '#6366f1' }}><Flame size={24} /></div>
            <div>
              <h4 style={{ fontSize: '1rem' }}>Sandboxed Evaluations</h4>
              <p style={{ fontSize: '0.85rem' }}>Features local JS code compilation within isolated virtual execution scopes.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <div style={{ color: '#6366f1' }}><BookOpen size={24} /></div>
            <div>
              <h4 style={{ fontSize: '1rem' }}>Autogenerated Certificates</h4>
              <p style={{ fontSize: '0.85rem' }}>Checks course eligibility dynamically and renders landscape PDF files automatically.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <div style={{ color: '#6366f1' }}><Settings size={24} /></div>
            <div>
              <h4 style={{ fontSize: '1rem' }}>Jitsi video conferencing</h4>
              <p style={{ fontSize: '0.85rem' }}>Generates private, secure virtual class links on scheduling live sessions.</p>
            </div>
          </div>
        </div>
      </div>

      <div className="glass-card">
        <h3 style={{ fontSize: '1.25rem', marginBottom: '0.75rem' }}>Developer & Accreditation Board</h3>
        <p>Built with pair-programming assistance from Antigravity, a coding assistant by the Google DeepMind team. The system implements all 17 modules outlined in the project specifications.</p>
      </div>
    </div>
  );
};

export default About;
